rpc = "https://api.cartridge.gg/x/starknet/sepolia"
world_address = "0x0035a61193deacca08e9438fc102a8fd6c9a8f6d1de392fd61277022793b9a3f"

[indexing]
allowed_origins = ["https://dark-waters-m2fn.vercel.app", "http://localhost:3000"]
index_pending = true
index_transactions = false
polling_interval = 1000
